### PR TITLE
fix: pin @openapi-contrib/openapi-schema-to-json-schema version to ~3.2.0 to resolve ESM issues

### PR DESCRIPTION
**Pull request by hrkeni**
fix: pin @openapi-contrib/openapi-schema-to-json-schema version to ~3.2.0 to resolve ESM issues

**Related issue(s)**
Resolves https://github.com/asyncapi/generator/issues/927

### CODE REVIEW

**Comment by jonaslagoni** [comment]
Resolved the cli issue as well https://github.com/asyncapi/cli/issues/491

**Review by fmvilas — APPROVED** [review]
Good catch. Thanks for the PR! 🙌

**Review by fmvilas — CHANGES_REQUESTED** [review]
Just saw tests are failing. Would you mind having a look?

**Comment by derberg** [comment]
I don't get why is this happening, package-lock is fixed to `3.1.0` and `3.3.0` should not be installed 🤔

**Comment by derberg** [comment]
ok, I still don't get why this change is needed and how it solves the problem as:
- only `package.json` is update and `package-lock.json` is still set to 3.1
- since package-lock is in place, why 3.3 is used

@hrkeni regarding failing test please update https://github.com/asyncapi/openapi-schema-parser/blob/master/test/parse_test.js#L12 with the following:

```
const outputWithOpenAPI = '{"asyncapi":"2.0.0","info":{"title":"My API","version":"1.0.0"},"channels":{"mychannel":{"publish":{"message":{"payload":{"type":["object","null"],"properties":{"name":{"type":"string","x-parser-schema-id":"<anonymous-schema-2>"},"discriminatorTest":{"discriminator":"objectType","oneOf":[{"type":"object","properties":{"objectType":{"type":"string","x-parser-schema-id":"<anonymous-schema-5>"},"prop1":{"type":"string","x-parser-schema-id":"<anonymous-schema-6>"}},"x-parser-schema-id":"<anonymous-schema-4>"},{"type":"object","properties":{"objectType":{"type":"string","x-parser-schema-id":"<anonymous-schema-8>"},"prop2":{"type":"string","x-parser-schema-id":"<anonymous-schema-9>"}},"x-parser-schema-id":"<anonymous-schema-7>"}],"x-parser-schema-id":"<anonymous-schema-3>"},"test":{"type":"object","properties":{"testing":{"type":"string","x-parser-schema-id":"<anonymous-schema-11>"}},"x-parser-schema-id":"<anonymous-schema-10>"}},"examples":[{"name":"Fran"}],"x-parser-schema-id":"<anonymous-schema-1>"},"x-parser-original-schema-format":"application/vnd.oai.openapi;version=3.0.0","x-parser-original-payload":{"type":"object","nullable":true,"example":{"name":"Fran"},"properties":{"name":{"type":"string","x-parser-schema-id":"<anonymous-schema-12>"},"discriminatorTest":{"discriminator":"objectType","oneOf":[{"type":"object","properties":{"objectType":{"type":"string","x-parser-schema-id":"<anonymous-schema-5>"},"prop1":{"type":"string","x-parser-schema-id":"<anonymous-schema-6>"}},"x-parser-schema-id":"<anonymous-schema-4>"},{"type":"object","properties":{"objectType":{"type":"string","x-parser-schema-id":"<anonymous-schema-8>"},"prop2":{"type":"string","x-parser-schema-id":"<anonymous-schema-9>"}},"x-parser-schema-id":"<anonymous-schema-7>"}],"x-parser-schema-id":"<anonymous-schema-13>"},"test":{"type":"object","properties":{"testing":{"type":"string","x-parser-schema-id":"<anonymous-schema-15>"}},"x-parser-schema-id":"<anonymous-schema-14>"}},"x-parser-schema-id":"testSchema"},"schemaFormat":"application/vnd.aai.asyncapi;version=2.0.0","x-parser-message-parsed":true,"x-parser-message-name":"testMessage"}}}},"components":{"messages":{"testMessage":{"payload":{"type":["object","null"],"properties":{"name":{"type":"string","x-parser-schema-id":"<anonymous-schema-2>"},"discriminatorTest":{"discriminator":"objectType","oneOf":[{"type":"object","properties":{"objectType":{"type":"string","x-parser-schema-id":"<anonymous-schema-5>"},"prop1":{"type":"string","x-parser-schema-id":"<anonymous-schema-6>"}},"x-parser-schema-id":"<anonymous-schema-4>"},{"type":"object","properties":{"objectType":{"type":"string","x-parser-schema-id":"<anonymous-schema-8>"},"prop2":{"type":"string","x-parser-schema-id":"<anonymous-schema-9>"}},"x-parser-schema-id":"<anonymous-schema-7>"}],"x-parser-schema-id":"<anonymous-schema-3>"},"test":{"type":"object","properties":{"testing":{"type":"string","x-parser-schema-id":"<anonymous-schema-11>"}},"x-parser-schema-id":"<anonymous-schema-10>"}},"examples":[{"name":"Fran"}],"x-parser-schema-id":"<anonymous-schema-1>"},"x-parser-original-schema-format":"application/vnd.oai.openapi;version=3.0.0","x-parser-original-payload":{"type":"object","nullable":true,"example":{"name":"Fran"},"properties":{"name":{"type":"string","x-parser-schema-id":"<anonymous-schema-12>"},"discriminatorTest":{"discriminator":"objectType","oneOf":[{"type":"object","properties":{"objectType":{"type":"string","x-parser-schema-id":"<anonymous-schema-5>"},"prop1":{"type":"string","x-parser-schema-id":"<anonymous-schema-6>"}},"x-parser-schema-id":"<anonymous-schema-4>"},{"type":"object","properties":{"objectType":{"type":"string","x-parser-schema-id":"<anonymous-schema-8>"},"prop2":{"type":"string","x-parser-schema-id":"<anonymous-schema-9>"}},"x-parser-schema-id":"<anonymous-schema-7>"}],"x-parser-schema-id":"<anonymous-schema-13>"},"test":{"type":"object","properties":{"testing":{"type":"string","x-parser-schema-id":"<anonymous-schema-15>"}},"x-parser-schema-id":"<anonymous-schema-14>"}},"x-parser-schema-id":"testSchema"},"schemaFormat":"application/vnd.aai.asyncapi;version=2.0.0","x-parser-message-parsed":true,"x-parser-message-name":"testMessage"}},"schemas":{"testSchema":{"type":"object","nullable":true,"example":{"name":"Fran"},"properties":{"name":{"type":"string","x-parser-schema-id":"<anonymous-schema-12>"},"discriminatorTest":{"discriminator":"objectType","oneOf":[{"type":"object","properties":{"objectType":{"type":"string","x-parser-schema-id":"<anonymous-schema-5>"},"prop1":{"type":"string","x-parser-schema-id":"<anonymous-schema-6>"}},"x-parser-schema-id":"<anonymous-schema-4>"},{"type":"object","properties":{"objectType":{"type":"string","x-parser-schema-id":"<anonymous-schema-8>"},"prop2":{"type":"string","x-parser-schema-id":"<anonymous-schema-9>"}},"x-parser-schema-id":"<anonymous-schema-7>"}],"x-parser-schema-id":"<anonymous-schema-13>"},"test":{"type":"object","properties":{"testing":{"type":"string","x-parser-schema-id":"<anonymous-schema-15>"}},"x-parser-schema-id":"<anonymous-schema-14>"}},"x-parser-schema-id":"testSchema"}}},"x-parser-spec-parsed":true}';
```

there were errors in tests and never fixed before

**Comment by jonaslagoni** [comment]
@derberg my current assumption is that once you use `^` in as dependency version in the package, the dependency manager is free to use the newest version (within that major version), regardless of what is specified in package lock.

**Comment by Gyllsdorff** [comment]
> my current assumption is that once you use ^ in as dependency version in the package, the dependency manager is free to use the newest version (within that major version), regardless of what is specified in package lock.

`package.json` sets the possible and allowed version ranges for direct dependencies and possibly some constraints on transitive dependencies through the `overrides` directive. 

`package-lock.json` sets the _exact_ version and hash of the version that should be installed. 

The tricky part is that different `npm` commands will handle this slightly different. `npm install` for example can update the version in `package-lock.json` in some npm versions. `npm ci` on the other hand usually does what we expect it to.

**Review by fmvilas — APPROVED** [review]
LGTM 👍

**Comment by derberg** [comment]
there are some issues with actions, they do not get events from GH. We need to wait.

Screenshot 2023-03-29 at 16 36 35

**Pull request merged**
